version: '3'

services:

  # common-php:
  #   image: php:7.4.2-fpm
  #   container_name: common-php

  # common-nginx:
  #   image: nginx:1.17.8-alpine
  #   container_name: common-nginx
  #   ports:
  #     - 80:80

  common-mysql:
    image: mysql:5.7.29
    container_name: common-mysql
    restart: always
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION" # to set sql mode like staging sql mode
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql

  common-pma:
    image: phpmyadmin/phpmyadmin
    container_name: common-pma
    restart: always
    environment:
      PMA_HOST: common-mysql
      PMA_PORT: 3306
    ports:
      - 8001:80
