apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: db0
    user: admin
    password: 123456
    url: http://common-influxdb:8086
    isDefault: true
    editable: true